const types_teste = {
    CART_OPEN: "CART_OPEN",
    PROD_OPEN: "PROD_OPEN",
    CATEGORY_OPEN : "CATEGORY_OPEN",
    CART_ADD : "CART_ADD",
    CART_REMOVE : "CART_REMOVE",
    CART_INCREASE : "CART_INCREASE",
    CART_DECREASE : "CART_DECREASE",
    LOGIN_REDIRECT : "LOGIN_REDIRECT"
}

export default types_teste